stages:
  - build
  - test
  - deploy


# Этот блок должен быть на самом верхнем уровне файла, без каких-либо отступов слева
.docker_login_template: &docker_login_template
  before_script:
    # 1. Обязательно заключаем строку в кавычки из-за символа ':'
    - 'echo "CI_REGISTRY is: $CI_REGISTRY"' # <--- ВОТ ТАК! В одинарных или двойных кавычках
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    # 2. Эту строку тоже лучше заключить в кавычки, чтобы избежать будущих проблем с ':'
    - 'echo "Attempting to push to image: $CI_REGISTRY_IMAGE"'


.kube_config_template: &kube_config_template
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
    - chmod 600 ~/.kube/config
    - export KUBECONFIG=~/.kube/config
    - kubectl config use-context default-context

build_job:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
      command: ["dockerd", "--host=tcp://0.0.0.0:2375", "--host=unix:///var/run/docker.sock", "--insecure-registry=192.168.50.11:4567"]
  tags:
    - docker
  <<: *docker_login_template
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  artifacts:
    paths:
      - k8s-deploy.yaml
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'


test_job:
  stage: test
  image: golang:1.23-alpine
  tags:
    - kubernetes
  script:
    - cd /builds/$CI_PROJECT_PATH
    - go mod tidy
    - go test -v ./...
  needs:
    - build_job
  rules:
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'

deploy_job:
  stage: deploy
  image: bitnami/kubectl:latest
  tags:
    - kubernetes
  <<: *kube_config_template
  script:
    - NAMESPACE="my-go-app"
    - kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f - || true
    - sed -i "s|<YOUR_DOCKERHUB_USERNAME>/go-app:latest|$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA|g" k8s-deploy.yaml
    - kubectl apply -f k8s-deploy.yaml
    - kubectl rollout status deployment/go-app-deployment -n $NAMESPACE
  needs:
    - build_job
    - test_job

  rules:
    - if: '$CI_COMMIT_TAG'